/** All test data generated by this factory carries the __E2E__ marker. */

export const E2E_MARKER = "__E2E__";

export type JobPayload = {
  keyword: string;
  noteAccountId: number;
  promptTemplateId: number;
  referenceMaterialIds: number[];
  monetizationEnabled: boolean;
  salesMode: "normal" | "free_paid";
  desiredPriceYen: number | null;
  additionalInstruction: string;
};

export type SaveNotePayload = {
  forceMethod: "unofficial_api" | "playwright" | "pinchtab" | null;
  noteAccountId: number;
  applySaleSettings: boolean;
};

export function makeJobPayload(
  overrides: Partial<JobPayload> & { runId: string }
): JobPayload {
  const { runId, ...rest } = overrides;
  return {
    keyword: `${E2E_MARKER} テスト記事 ${runId}`,
    noteAccountId: 1,
    promptTemplateId: 1,
    referenceMaterialIds: [],
    monetizationEnabled: false,
    salesMode: "normal",
    desiredPriceYen: null,
    additionalInstruction: `自動検証用記事 runId=${runId}`,
    ...rest,
  };
}

export function makePaidJobPayload(overrides: Partial<JobPayload> & { runId: string }): JobPayload {
  return makeJobPayload({
    monetizationEnabled: true,
    salesMode: "free_paid",
    desiredPriceYen: 300,
    ...overrides,
  });
}

export function makeSavePayload(
  overrides: Partial<SaveNotePayload> = {}
): SaveNotePayload {
  return {
    forceMethod: null,
    noteAccountId: 1,
    applySaleSettings: false,
    ...overrides,
  };
}

/** Generates a run ID with a timestamp suffix for artifact directory names. */
export function makeRunId(prefix: string): string {
  const ts = new Date()
    .toISOString()
    .replace(/[-:]/g, "")
    .replace("T", "T")
    .slice(0, 15); // YYYYMMDDTHHMMSS
  return `${prefix}-${ts}`;
}
